# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dbscan_int <- function(data, eps, minPts, borderPoints, type, bucketSize, splitRule, approx) {
    .Call('dbscan_dbscan_int', PACKAGE = 'dbscan', data, eps, minPts, borderPoints, type, bucketSize, splitRule, approx)
}

kNNdist_int <- function(data, k, type, bucketSize, splitRule, approx) {
    .Call('dbscan_kNNdist_int', PACKAGE = 'dbscan', data, k, type, bucketSize, splitRule, approx)
}

